const ProjectList = [
  {
    id: 1,
    category: "Blog",
    title: "First Website i ever created",
    img: "/projects/1.png",
    altImg: "1.png",
    dateFinished: "2018",
    liveView: "https://soethiono.blogspot.com/",
  },
  {
    id: 2,
    category: "Portfolio",
    title: "My First Portfolio",
    img: "/projects/2.png",
    altImg: "2.png",
    dateFinished: "2020",
    liveView: "https://irfankurniawansuthiono.github.io/projek-1/",
    repository: "https://github.com/irfankurniawansuthiono/projek-1",
  },
  {
    id: 3,
    category: "Portfolio",
    title: "My Second Portfolio",
    img: "/projects/3.png",
    altImg: "3.png",
    dateFinished: "2021",
    liveView: "https://irfankurniawansuthiono.github.io/",
    repository:
      "https://github.com/irfankurniawansuthiono/irfankurniawansuthiono.github.io",
  },
  {
    id: 4,
    category: "E-Learning",
    title: "BiimBel v1",
    img: "/projects/4.png",
    altImg: "4.png",
    dateFinished: "2022",
    liveView: "https://biimbel.netlify.app/",
    repository: "https://github.com/irfankurniawansuthiono/tugas-akhir-sem2",
  },
  {
    id: 5,
    category: "Game",
    title: "GTPS 7",
    img: "/projects/5.png",
    altImg: "5.png",
    dateFinished: "2022",
    liveView: "https://gtps7.vercel.app/",
    repository: "https://github.com/irfankurniawansuthiono/gtps7",
  },
  {
    id: 6,
    category: "Apps",
    title: "Book Shelf - DICODING",
    img: "/projects/6.png",
    altImg: "6.png",
    dateFinished: "2023",
    liveView: "https://book-shelf-apps-by-irfan.vercel.app/",
    repository:
      "https://github.com/irfankurniawansuthiono/book-shelf-apps-dicoding/tree/main",
  },
  {
    id: 7,
    category: "Apps",
    title: "Note - DICODING",
    img: "/projects/7.png",
    altImg: "7.png",
    dateFinished: "2023",
    liveView: "https://dicoding-note-app-submission.vercel.app/",
    repository:
      "https://github.com/irfankurniawansuthiono/dicoding-note-app-submission",
  },
  {
    id: 8,
    category: "Game",
    title: "GrowNet",
    img: "/projects/8.png",
    altImg: "8.png",
    dateFinished: "2023",
    liveView: "https://www.grownet.site/",
  },
  {
    id: 9,
    category: "Apps",
    title: "Note v2 - DICODING",
    img: "/projects/9.png",
    altImg: "9.png",
    dateFinished: "2023",
    liveView: "https://dicoding-menengah-submission1-hosting.vercel.app/",
    repository:
      "https://github.com/irfankurniawansuthiono/Dicoding_menegah_Submission_1",
  },
  {
    id: 10,
    category: "Apps",
    title: "Contact - DICODING",
    img: "/projects/10.png",
    altImg: "10.png",
    dateFinished: "2023",
    liveView: "https://contactappbyirfan.vercel.app/",
    repository:
      "https://github.com/irfankurniawansuthiono/dicoding-menengah-contact-app/tree/main",
  },
  {
    id: 11,
    category: "E-Learning",
    title: "BiimBel v2",
    img: "/projects/11.png",
    altImg: "11.png",
    dateFinished: "2023",
    liveView: "https://www.biimbel.my.id/",
    repository: "https://github.com/irfankurniawansuthiono/BiimBel-source-code",
  },
  {
    id: 12,
    category: "E-Learning",
    title: "BiimBel Admin v2",
    img: "/projects/12.png",
    altImg: "12.png",
    dateFinished: "2023",
    liveView: "https://admin.biimbel.my.id/",
    repository:
      "https://github.com/irfankurniawansuthiono/admin-biimbel-source-code",
  },
  {
    id: 13,
    category: "Apps",
    title: "Note v3 - DICODING",
    img: "/projects/13.png",
    altImg: "13.png",
    dateFinished: "2023",
    liveView: "https://dicoding-note-app-v3.vercel.app/",
    repository:
      "https://github.com/irfankurniawansuthiono/dicoding-menengah-note-app-v3-source-code",
  },
  {
    id: 14,
    category: "Portfolio",
    title: "My Third Portfolio",
    img: "/projects/14.png",
    altImg: "14.png",
    dateFinished: "2023",
    liveView: "https://irfanks.vercel.app/",
    repository: "https://github.com/irfankurniawansuthiono/portfolio-v3",
  },
];

export default ProjectList;
